# Generated by Django 4.0.4 on 2022-05-12 14:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0002_rename_users_myusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=255)),
                ('users', models.ManyToManyField(to='mainapp.myusers')),
            ],
        ),
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('edit_date', models.DateField(auto_now=True)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('create_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.myusers')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todo.project')),
            ],
        ),
    ]
